export const foods = [
  {
    id: "1",
    image: "images/burger.jpg",
    title: "Classic Chicken Burger",
    description: "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod.",
    discount: 20,
    price: 20,
    rating: 4.00,
  },
  {
    id: "2",
    image: "images/pizza.jpg",
    title: "Pepperoni Chicken Pizza",
    description: "Dolor sit amet lorem ipsum consectetur adipiscing elit sed do eiusmod.",
    discount: 0,
    price: 25,
    rating: 5.00,
  },
  {
    id: "3",
    image: "images/roast-beef.jpg",
    title: "Roast Beef Plate",
    description: "Ipsum dolor sit amet consectetur adipiscing elit sed do tempor incididunt.",
    discount: 10,
    price: 30,
    rating: 3.00,
  },
  {
    id: "4",
    image: "images/berry.webp",
    title: "Mixed Berry Bowl",
    description: "Consectetur adipiscing elit lorem ipsum dolor sit amet sed do eiusmod.",
    discount: 5,
    price: 12,
    rating: 5.00,
  },
  {
    id: "5",
    image: "images/soup.jpg",
    title: "Chicken Veggie Soup",
    description: "Adipiscing elit lorem ipsum dolor sit amet sed do tempor incididunt.",
    discount: 0,
    price: 10,
    rating: 4.00,
  },
  {
    id: "6",
    image: "images/salmon.jpg",
    title: "Grilled Salmon Fillet",
    description: "Lorem ipsum dolor sit amet consectetur elit sed do tempor incididunt.",
    discount: 18,
    price: 35,
    rating: 5.00,
  },
  {
    id: "7",
    image: "images/roast-beef.jpg",
    title: "Beef Cheese Sandwich",
    description: "Sit amet lorem ipsum dolor consectetur adipiscing elit sed do eiusmod.",
    discount: 0,
    price: 18,
    rating: 3.00,
  },
  {
    id: "8",
    image: "images/berry.webp",
    title: "Spicy Veggie Wrap",
    description: "Lorem ipsum dolor sit amet consectetur adipiscing elit sed eiusmod.",
    discount: 10,
    price: 15,
    rating: 4.00,
  },
  {
    id: "9",
    image: "images/chicken.jpg",
    title: "Glazed Chicken Wings",
    description: "Adipiscing elit sed do eiusmod lorem ipsum dolor sit amet consectetur.",
    discount: 25,
    price: 22,
    rating: 5.00,
  }
]
